### ISSUE TITLE
Submenu not opened when you visit page that belongs to a submenu

### ISSUE THREAD

**Issue by bichotll** [pedronauck/docz#136]
## Bug Report

The submenu is closed when you visit a page straight away from the browser.

**To Reproduce**

Example: https://reactpixi.org/#/components/particle-container
Note that the page belongs to the menu "Components", but it's closed.

**Expected behavior**

The menu should be opened. Otherwise it feels like the page does not belong to the web and you lose the track of where it comes from.

**Additional context/Screenshots**

![image](https://user-images.githubusercontent.com/643359/42657700-58d5f9f8-8623-11e8-9904-cea8619e3c38.png)

**Comment by pedronauck** [comment]
thanks @bichotll, this is a clear UX bug. I'll fix that more quick as possible ✌️

**Comment by pedronauck** [comment]
Fixed on [v0.6.0](https://github.com/pedronauck/docz/releases/tag/v0.6.0) 🚀

**Comment by lapidus** [comment]
Still does not seem to work on 0.10.3.
The menu closes directly after clicking any component. And it doesn't open when navigating directly to a component.

**Comment by mzedeler** [comment]
@pedronauck: this should be reopened. For instance, if I have this menu:

 * My fancy components
  * Component A
  * Component B

And I click "Component A", the whole menu closes. This is confusing.

**Comment by phatNfqAsia** [comment]
> @pedronauck: this should be reopened. For instance, if I have this menu:
> 
> * My fancy components
>   
>   * Component A
>   * Component B
> 
> And I click "Component A", the whole menu closes. This is confusing.

I have the same problem here

**Comment by sunkeysun** [comment]
I alse have this problem on v0.13.7. does bug really be fixed ?

**Comment by idmontie** [comment]
Looks like the NavLink in https://github.com/pedronauck/docz/blob/master/packages/docz/src/components/Link.tsx is not getting an `isActive` prop from ManuLink https://github.com/pedronauck/docz/blob/master/packages/docz-theme-default/src/components/shared/Sidebar/MenuLink.tsx#L105.

I think re-using this function would work: https://github.com/pedronauck/docz/blob/21d58fba79aeaeeb1d460d93a1fb8429289f225e/packages/docz-theme-default/src/components/shared/Sidebar/MenuHeadings.tsx#L54

I'll try it out tonight and make a PR.

**Comment by pedronauck** [comment]
Closed in the newest release.
