### ISSUE TITLE
PropsTable does not render 

### ISSUE THREAD

**Issue by brunolemos** [pedronauck/docz#227]
## Bug Report

PropsTable did not render anything in the screen. (cc #138)
I'm using TypeScript.

**To Reproduce**
```mdx
---
name: Button
---

import { PropsTable } from 'docz'

import Button from './Button'

# Button

<Button onPress={() => alert('pressed')}>Click</Button>

<PropsTable of={Button} />
```

```tsx
import React from 'react'
import { StyleSheet, Text, Touchable } from 'react-primitives'

const styles = StyleSheet.create({
  text: {
    color: 'green',
  },
})

export interface ButtonProps {
  test?: string
  children: string
}

const Button: React.SFC<ButtonProps> = props => (
  <Touchable {...props}>
    <Text style={styles.text}>{props.children}</Text>
  </Touchable>
)

export default Button
```

**Expected behavior**

Render PropsTable, getting props from TypeScript interface automatically

**Environment**

* OS: macOS 10.14
* Node/npm version: Node 8/npm 5

**Additional context/Screenshots**

![image](https://user-images.githubusercontent.com/619186/44124946-40234490-a006-11e8-8a5c-0e1c9fcc89fc.png)

**Comment by mrac** [comment]
I had the same issue. The problem was import line for 'react'.
`import * as React from 'react'` helped.

**Comment by mdapper** [comment]
Same bug here, only worked with @mrac suggestion.

It's possible that Docz, or other dependencie that handle the PropsTable, don't work with the following TypeScript setting?

```
 {
  "compilerOptions": {
    ...
    "allowSyntheticDefaultImports": true,
    ...
  },
}
```

**Comment by JeroenReumkens** [comment]
You guys are right that `import * as React from 'react';` does solve the issue. But for most of us that's probably not a viable solution.

Right now I'm searching if there is a way to override the tsconfig to set this option to true like I have in my main project as well. As soon as I have found a solution I'll post back here.

**Comment by markusoelhafen** [comment]
I already had `import * as React from 'react';` but the props table still didn't render.

What did the trick, was changing the default exported element with lowercase instead of camelcase.

so, this didn't render the table:
```
const Input: React.StatelessComponent<InputProps> = (props): JSX.Element => (
  <StyledInput {...props} />
);

export default Input;
```

but this did:
```
const input: React.St...

export default input;
```

I would still rather use camelcase for my constants, any chance to solve this?

**Comment by JeroenReumkens** [comment]
@markusoelhafen That's actually very strange. For me it did work with PascalCase. But I also notice that you are using a functional component, which I didn't. Maybe that also makes a difference. 
Unfortunately I still haven't been able to find a fix for this problem.

**Comment by strothj** [comment]
Try changing `export default Input;` to `export { Input };` or adding exporting as a named export in addition to the default export.

**Comment by markusoelhafen** [comment]
Hey @strothj , 
named exports fixed the problem, and now everything is running smoothly 👍 
thx!

**Comment by JeroenReumkens** [comment]
I haven't had the time to try named exports, I'll assume that works. But still one might want to have default exports, since this is a pretty common thing. I don't like changing my code base for a specific tool I use to render documentation. So I'm still hoping someone will pass by with the solution that works in all cases 😄

**Comment by markusoelhafen** [comment]
Hey @JeroenReumkens,
We still have default exports, but we explicitly made the components named exports [here](https://github.com/markusoelhafen/todo-app-pwa).

Now that it works I'm pretty happy with docz :)

**Comment by JeroenReumkens** [comment]
@markusoelhafen  Yeah exactly, so you just do both? Still not totally comfortable with the solution, since other developers constantly need the explanation why we do that. 
Maybe if this works, it might also work if we use `import { default as ComponentName } from './Component'` then? I'm going to give that a try somewhere this week.

**Comment by markusoelhafen** [comment]
@JeroenReumkens Gave it a quick try, but didn't work with import `{ default as ComponentName } from './Component'`.
Maybe this issue somehow relates to [this issue](https://github.com/styleguidist/react-docgen-typescript/issues/113) at `react-docgen-typescript`?

**Comment by strothj** [comment]
```
export const Input: React.StatelessComponent<InputProps> = (props): JSX.Element => (
  <StyledInput {...props} />
);

export default Input;
```

If I'm not mistaken, adding an additional named export along with the default may work. That way you can continue to use the default export but the parser will be able to attach the docgen information to it.

**Comment by JeroenReumkens** [comment]
I've just tried to get it to work, but unfortunately it didn't. I even tried making a very small component (tried but functional and class), which also didn't work. 

Example:
```
interface PriceProps {
  value: string | number;
}

const Test = (props: PriceProps) => <div>{props.value}</div>;
// Price was also defined. 
export { Price, Test };
```

The difference might be that I'm using the babel-6 plugin? I have planned to upgrade that in the coming weeks, but it would be great if I could get Docz running before that.

**Comment by three60five** [comment]
I am not using Typescript in my project. What is the solution to using `PropsTable` component?

**Comment by pedronauck** [comment]
Please guys, can you test with the [new release](https://github.com/pedronauck/docz/releases/edit/v0.11.0)... I think that this was fixed!

**Comment by wceolin** [comment]
Thanks for the update, @pedronauck. It still doesn't render in my case (using with Styled Components - as discussed in #156).

I saw some people mentioned they'd start working on that but I didn't see any further updates about it. Are you working with them to make docz compatible with styled components? Do you need any help/is there a way to collaborate?

**Comment by JeroenReumkens** [comment]
Hey,

I was testing the same thing yesterday. Didn’t render either 😢 I’m not using styled components but do use Typescript, and Babel 6. For the latter I read there were some problems with, so i’m trying to upgrade to Babel 7 and will test again after that. But that is going to take a few days before I can test that. 

Thanks for all the hard work @pedronauck !

**Comment by wceolin** [comment]
@pedronauck Thanks, I had seen that example but I'm trying to figure out a solution without having to update all components 😅

**Comment by smakosh** [comment]
Having the same issue as @wceolin

**Comment by yiyeum** [comment]
I've tried `import * as React from 'react'` but doesn't work.
Using ` docz: ^1.3.2` with react / typescript.

ex) Button folder has `index.tsx` with export const Button and `doc.mdx` with
```
import { Props } 'docz';
import { Button } from './';
<Props of={Button} />
```  

but doesn't render prop table...
