### ISSUE TITLE
Avoid global styles to break components

### ISSUE THREAD

**Issue by Grsmto** [pedronauck/docz#398]
## Bug Report

**Describe the bug**
In `docz-theme-default` some global styles are applied which are reaching components and breaking the styles on some scenarios:

```
*, *:before, *:after {
    box-sizing: border-box;
  }
```

All my components will receive `box-sizing: border-box;`.

These global rules could be easily avoided by using the `box-sizing` properties on the necessary elements directly.

*A clear and concise description of what the bug is.*
`docz-theme-default` global styles are leaking to consumer components.

**To Reproduce**
I guess this is self explanatory.

**Expected behavior**
Styles from `docz-theme-default` should not impact on consumer components.

I can provide a PR for this if maintainers think this is a valid issue.

**Comment by kylealwyn** [comment]
Also experiencing this on the dark theme and the global font color leaking into the live preview:
 
![screen shot 2018-10-16 at 10 42 55 am](https://user-images.githubusercontent.com/14184138/47035993-4a4d1080-d130-11e8-8fc5-be4ad7f285b1.png)

**Comment by mergebandit** [comment]
While this is one example, for non-trivial implementations / themes I think it could be a common problem in the wild.

Storybook mitigates this by wrapping each component in an `iframe`. We're working on a [Storybook to DocZ bridge](https://github.com/hydrateio/docz-plugin-storybook) right now, and one of the things we're exploring is wrapping our components in either an iframe or potentially using shadow dom (yay component heights being respected!) to encapsulate each of the story components.

**Comment by jedrichards** [comment]
Using `all: initial`, possibly with help from a postcss plugin could be a practical way to achieve an element level CSS reset.

https://developer.mozilla.org/en-US/docs/Web/CSS/initial
https://github.com/maximkoretskiy/postcss-autoreset

**Comment by pedronauck** [comment]
Fixed on the new release [v0.12.10](https://github.com/pedronauck/docz/releases/tag/v0.12.10) ✅

**Comment by pedronauck** [comment]
I removed normalize.css from theme default and the classes and styles applied to Playground are fixed too!

**Comment by kachkaev** [comment]
Looks like this bug still occurs in the latest version. I just cloned the repo and launched the basic example with just the following added lines to [packages/docz-theme-default/src/styles/global.ts](https://github.com/pedronauck/docz/blob/master/packages/docz-theme-default/src/styles/global.ts#L11):

```css
* {
  box-sizing: border-box !important;
}
```

Here's the result:

<img width="684" alt="screenshot 2019-01-11 at 21 32 10" src="https://user-images.githubusercontent.com/608862/51060664-60138a00-15e8-11e9-9320-fe6e2932ba00.png">

(notice gaps next to the resizer)
