### ISSUE TITLE
Error: Callback was already called.

### ISSUE THREAD

**Issue by ashutosh1211** [pedronauck/docz#428]
C:\prj\>yarn doc:dev
yarn run v1.9.4
$ docz dev
(node:12720) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

Compiling

* Client █████████████████████████ building modules (10%) 7/14 modules 7 active
  node_modules\regenerator-runtime\runtime.js

C:\prj\\node_modules\neo-async\async.js:14
    throw new Error('Callback was already called.');
    ^

Error: Callback was already called.
    at throwError (C:\prj\\node_modules\neo-async\async.js:14:11)
    at C:\prj\\node_modules\neo-async\async.js:2805:7
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by nicholasess** [comment]
@ashutosh1211 The error isn't of docz, upgrade your package called neo-async

**Comment by ashutosh1211** [comment]
@nicholasess I don't have any package named neo-async in my package.json. What should I do?

**Comment by ashutosh1211** [comment]
Resolved, It was because of `webpack-hot-client` package, after removing `webpack-hot-client` docz started successfully.

**Comment by varshitha100** [comment]
hi where we have to remove that webpack-hot-client one because when i uninstalled that webpack-hot one still showing same error
