### ISSUE TITLE
Error occurred while using docz dev

### ISSUE THREAD

**Issue by leftstick** [pedronauck/docz#797]
## Bug Report

**Describe the bug**

Error occurred as below:

```
index.js:1 Warning: Invalid prop `entries` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props.
    in Fragment (created by MDXCreateElement)
    in MDXCreateElement (at home.mdx:20)
    in MDXContent (created by AsyncComponent)
    in AsyncComponent (created by ExportedComponent)
    in ExportedComponent (created by InnerLoadable)
    in InnerLoadable (created by Context.Consumer)
    in Component (created by ForwardRef)
    in ForwardRef (created by AsyncRoute)
    in div (created by Context.Consumer)
    in StyledComponent (created by styled.div)
    in styled.div (created by Page)
    in div (created by Context.Consumer)
    in StyledComponent (created by styled.div)
    in styled.div (created by Page)
    in div (created by Context.Consumer)
    in StyledComponent (created by styled.div)
    in styled.div (created by Page)
    in Page (created by AsyncRoute)
    in AsyncRoute (created by Routes)
    in div (created by FocusHandlerImpl)
    in FocusHandlerImpl (created by Context.Consumer)
    in FocusHandler (created by RouterImpl)
    in RouterImpl (created by Context.Consumer)
    in Location (created by Context.Consumer)
    in Router (created by Routes)
    in LocationProvider (created by Routes)
    in a (created by Routes)
    in Routes (at root.jsx:13)
    in ComponentsProvider (created by Theme)
    in ThemeProvider (created by ThemeProvider)
    in ThemeProvider (created by Theme)
    in Theme
    in DoczStateProvider
    in Unknown (at root.jsx:12)
    in Root (created by HotExportedRoot)
    in AppContainer (created by HotExportedRoot)
    in HotExportedRoot (at app/index.jsx:14)
```

**To Reproduce**

1. Create an empty folder, for example: `docz-test`
2. Go into `docz-test`
3. Install dependencies `yarn add docz docz-theme-default --dev`
4. Create a `home.mdx` with content described in [getting-started-using](https://www.docz.site/docs/getting-started#using)
5. Start dev server with `npx docz dev`
6. Once open `http://localhost:3000`, you will see the above error in console

*In order to allow us to quickly reproduce you issue please include a link to a reproduction repository.*

https://github.com/leftstick/docz-test

**Expected behavior**

no error reported

**Environment**

* OS: macOs Mojave 10.14.4
* Node/npm version: node 11.12.0 / npm 6.7.0
* docz: 1.0.3

**Comment by fi3ework** [comment]
What is the version of your docz?

**Comment by leftstick** [comment]
docz: 1.0.3

**Comment by fi3ework** [comment]
Seems like a bug with mdx1.0? 🤔

**Comment by LucidityDesign** [comment]
Could be related to https://github.com/mdx-js/mdx/issues/530

**Comment by leftstick** [comment]
Close issue since it was fixed

**Comment by LucidityDesign** [comment]
Seems like the fix doesn't work.
@leftstick can you still reproduce the bug?

**Comment by leftstick** [comment]
@LucidityDesign  no, I cannot reproduce the issue now with `docz@1.0.4`, I believe the issue was fixed

**Comment by LucidityDesign** [comment]
For me the bug is gone with 1.1.0
