### ISSUE TITLE
[Typescript] Usage of Tagged Template Literal breaks Page

### ISSUE THREAD

**Issue by PhilippSpo** [pedronauck/docz#96]
## Bug Report

We are using styled-components for styling our components and since version 3.3.3 the way you declare prop types is improved/properly implemented. It works perfectly fine in our normal app. In docz the page using such a component is blank and there is no error message neither in the browser nor on the command line.

**To Reproduce**

1. Create a styled-component with type declaration
```jsx
const Flex = styled.div<{}>`
  display: flex;
`;
```
2. Import it in a `.mdx` file
3. See a blank page for that route

**Expected behavior**

Some error message that helps with debugging the issue further

**Enviroment**

* OS: OSX 10.13.5
* Node/npm version: Node 10.4/npm 6

**Comment by pedronauck** [comment]
I'm looking into it now @PhilippSpo ✌️

**Comment by pedronauck** [comment]
I thinking that this is an issue on [@babel/preset-typescript](https://www.npmjs.com/package/@babel/preset-typescript) 😕

For some reason, babel are keeping the typing definition:

```
var Flex = Object(styled_components__WEBPACK_IMPORTED_MODULE_0__["default"])('div') < FlexProps > "\n  display: flex;\n  background: ".concat(function (p) {
  return p.background;
}, ";\n");
```

**Comment by PhilippSpo** [comment]
@pedronauck Thanks for looking into it 🏆

Asking out of curiosity #noobAlert: When would one use `@babel/preset-typescript`? Doesn't the typescript Webpack loader already take care of transforming typescript to JS?

**Comment by pedronauck** [comment]
We're using `@babel/preset-typescript` instead of `ts-loader` for some performance issues. If you use just typescript, `ts-loader` can be a good option, but sometimes you need make some babel transformations with typescript, this makes bundler very slow... So, use just babel to transpile Typescript is better, but I think that babel has some bugs yet when transpile ts, I'm thinking creating an option to transpile with `ts-loader` or babel in docz, something like that:

```js
// doczrc.js
export default {
  typescript: true,
  typescriptTranspiler: 'tsloader' // and you can use 'babel' or 'tsloader' here
}
```

**Comment by PhilippSpo** [comment]
Thanks for explaining 😊Yeah such an option would be cool. We are currently using `awesome-typescript-loader` which has first-class integration with babel. Would that also be an option for docz?

**Comment by pedronauck** [comment]
Of course, `awesome-typescript-loader` can be an option too... But, what do you think in performance terms, which one is faster?

**Comment by PhilippSpo** [comment]
I don't know which one would be faster tbh. as I have only tried the `awesome-typescript-loader`. From the docs, though, I see that there are ways to improve the performance of it using e.g. caching.

**Comment by strothj** [comment]
Seems that this pull request to Babel is starting to progress:
https://github.com/babel/babel/pull/7754

This pull request covers the tagged templates

**Comment by strothj** [comment]
This should be fixed now with the latest Babel release `7.0.0-beta.55`

**Comment by dagatsoin** [comment]
Hi,
I am using docz@0.9.6

and I still have this issue.

```mdx
  <Text gutterBottom noWrap>
    {`
    Lorem ipsum dolor sit amet, consectetur adipisicing elit,
    sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    `}
  </Text>
```

leads to

```
Failed to compile.

./src/ui/components/text/Text.mdx
Module build failed (from ./node_modules/happypack/loader.js):
SyntaxError: /Users/fraktar/dev/saretec/client/src/ui/components/text/Text.mdx: Unexpected token, expected "}" (43:2)

  41 | <Text gutterBottom noWrap>
  42 |   {`
> 43 |   Lorem ipsum dolor sit amet, consectetur adipisicing elit,
     |   ^
  44 |   sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  45 |   `}
  46 | </Text>
    at _class.raise (/Users/fraktar/dev/saretec/client/node_modules/@babel/parser/lib/index.js:3898:15)
    at _class.unexpected (/Users/fraktar/dev/saretec/client/node_modules/@babel/parser/lib/index.js:5227:16)
    at _class.expect (/Users/fraktar/dev/saretec/client/node_modules/@babel/parser/lib/index.js:5215:28)
    at _class.jsxParseExpressionContainer (/Users/fraktar/dev/saretec/client/node_modules/@babel/parser/lib/index.js:3461:12)
    at _class.jsxParseAttributeValue (/Users/fraktar/dev/saretec/client/node_modules/@babel/parser/lib/index.js:3420:23)
    at _class.jsxParseAttribute (/Users/fraktar/dev/saretec/client/node_modules/@babel/parser/lib/index.js:3476:46)
    at _class.jsxParseOpeningElementAfterName (/Users/fraktar/dev/saretec/client/node_modules/@babel/parser/lib/index.js:3496:30)
    at _class.jsxParseOpeningElementAt (/Users/fraktar/dev/saretec/client/node_modules/@babel/parser/lib/index.js:3489:19)
    at _class.jsxParseElementAt (/Users/fraktar/dev/saretec/client/node_modules/@babel/parser/lib/index.js:3521:33)
    at _class.jsxParseElementAt (/Users/fraktar/dev/saretec/client/node_modules/@babel/parser/lib/index.js:3537:34)
    at _class.jsxParseElement (/Users/fraktar/dev/saretec/client/node_modules/@babel/parser/lib/index.js:3590:19)
    at _class.parseExprAtom (/Users/fraktar/dev/saretec/client/node_modules/@babel/parser/lib/index.js:3597:21)
    at _class.parseExprSubscripts (/Users/fraktar/dev/saretec/client/node_modules/@babel/parser/lib/index.js:5903:21)
    at _class.parseMaybeUnary (/Users/fraktar/dev/saretec/client/node_modules/@babel/parser/lib/index.js:5882:21)
    at _class.parseExprOps (/Users/fraktar/dev/saretec/client/node_modules/@babel/parser/lib/index.js:5791:21)
    at _class.parseMaybeConditional (/Users/fraktar/dev/saretec/client/node_modules/@babel/parser/lib/index.js:5763:21)
 @ ./.docz/app/imports.js 19:11-21:38
 @ ./.docz/app/root.jsx
 @ ./.docz/app/index.jsx
 @ multi ./node_modules/babel-polyfill/lib/index.js ./.docz/app/index.jsx
```

Note that the `package-lock.json` indicates the use of`Babel release 7.0.0-beta.55`

**Comment by dagatsoin** [comment]
Hi,
I am using docz@0.9.6

and I still have this issue.

```mdx
  <Text gutterBottom noWrap>
    {`
    Lorem ipsum dolor sit amet, consectetur adipisicing elit,
    sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    `}
  </Text>
```

leads to

```
Failed to compile.

./src/ui/components/text/Text.mdx
Module build failed (from ./node_modules/happypack/loader.js):
SyntaxError: /Users/XXX/dev/XXXX/client/src/ui/components/text/Text.mdx: Unexpected token, expected "}" (43:2)

  41 | <Text gutterBottom noWrap>
  42 |   {`
> 43 |   Lorem ipsum dolor sit amet, consectetur adipisicing elit,
     |   ^
  44 |   sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  45 |   `}
  46 | </Text>
    at _class.raise (/Users/XXX/dev/XXXX/client/node_modules/@babel/parser/lib/index.js:3898:15)
    at _class.unexpected (/Users/XXX/dev/XXXX/client/node_modules/@babel/parser/lib/index.js:5227:16)
    at _class.expect (/Users/XXX/dev/XXXX/client/node_modules/@babel/parser/lib/index.js:5215:28)
    at _class.jsxParseExpressionContainer (/Users/XXX/dev/XXXX/client/node_modules/@babel/parser/lib/index.js:3461:12)
    at _class.jsxParseAttributeValue (/Users/XXX/dev/XXXX/client/node_modules/@babel/parser/lib/index.js:3420:23)
    at _class.jsxParseAttribute (/Users/XXX/dev/XXXX/client/node_modules/@babel/parser/lib/index.js:3476:46)
    at _class.jsxParseOpeningElementAfterName (/Users/XXX/dev/XXXX/client/node_modules/@babel/parser/lib/index.js:3496:30)
    at _class.jsxParseOpeningElementAt (/Users/XXX/dev/XXXX/client/node_modules/@babel/parser/lib/index.js:3489:19)
    at _class.jsxParseElementAt (/Users/XXX/dev/XXXX/client/node_modules/@babel/parser/lib/index.js:3521:33)
    at _class.jsxParseElementAt (/Users/XXX/dev/XXXX/client/node_modules/@babel/parser/lib/index.js:3537:34)
    at _class.jsxParseElement (/Users/XXX/dev/XXXX/client/node_modules/@babel/parser/lib/index.js:3590:19)
    at _class.parseExprAtom (/Users/XXX/dev/XXXX/client/node_modules/@babel/parser/lib/index.js:3597:21)
    at _class.parseExprSubscripts (/Users/XXX/dev/XXXX/client/node_modules/@babel/parser/lib/index.js:5903:21)
    at _class.parseMaybeUnary (/Users/XXX/dev/XXXX/client/node_modules/@babel/parser/lib/index.js:5882:21)
    at _class.parseExprOps (/Users/XXX/dev/XXXX/client/node_modules/@babel/parser/lib/index.js:5791:21)
    at _class.parseMaybeConditional (/Users/XXX/dev/XXXX/client/node_modules/@babel/parser/lib/index.js:5763:21)
 @ ./.docz/app/imports.js 19:11-21:38
 @ ./.docz/app/root.jsx
 @ ./.docz/app/index.jsx
 @ multi ./node_modules/babel-polyfill/lib/index.js ./.docz/app/index.jsx
```

Note that the `package-lock.json` indicates the use of`Babel release 7.0.0-beta.55`
